server:
  port: 8070
eureka:
  instance:
    hostname: eureka-server
  client:
    fetchRegistry: false
    regiterWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/